//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class discharge
    {
        public int id_dis { get; set; }
        public Nullable<System.DateTime> date_dis { get; set; }
        public string reason { get; set; }
        public Nullable<int> id_pat { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
